name: Build LaTeX document
on:
  push:
    paths:
      - '**.tex'
      - '**.bib'
      - '**.sty'
      - '**/build_pdf.yml'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Commit files  
        run:
          sudo apt-get update
          
          sudo apt-get install texlive-full

          sudo apt-get install python3-pygments
          
          cd paper && make && cd ..
          
          git config --local user.name actions-user
          
          git config --local user.email "actions@github.com"
          
          cp paper/.aux/main.pdf .
          
          git add -f main.pdf;
          git commit -m "add generated pdf $(date)";
          git push -f origin ${GITHUB_REF##*/}
          
