# name: Build LaTeX document
# on:
#   push:
#     paths:
#       - '**.tex'
#       - '**.bib'
#       - '**.sty'
# jobs:
#   build_latex:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up Git repository
#         uses: actions/checkout@v3
#       - name: Compile LaTeX document
#         uses: xu-cheng/latex-action@v2
#         with:
#           root_file: main.tex
#           latexmk_shell_escape: true
#           args: -output-directory=.aux -pdf -file-line-error -halt-on-error -interaction=nonstopmode
#       - name: Commit files  
#         run:
#           git config --local user.name actions-user
          
#           git config --local user.email "actions@github.com"
          
#           cp .aux/main.pdf .
          
#           git add -f main.pdf;
#           git commit -m "add generated pdf $(date)";
#           git push -f origin ${GITHUB_REF##*/}
          
